### ISSUE TITLE
Custom Variable support for "Variable Aspect" function

### ISSUE THREAD

**Issue by HenriLK** [bitfocus/companion-module-bmd-teranex#21]
It would be really useful if we could use Custom Variables when executing the "Variable Aspect" function.
Currently the only way to set custom aspect values is to execute ALL parameters at once, which need to be hard coded into a function. So really the only current usefulness of this function is to make "preset" custom aspect ratios.

There are many possible case use for supporting variables in the "Variable Aspect" function but here are a few that apply to me:
1. Allow an end user to input specific width or heigh to be executed whilst maintaining current position or trim (assuming these were defined by a custom variable also).
2. Allow an end user to execute both H-Size and V-Size proportionately whilst only inputing one of the two values.
3. Allow an end user to choose from a number of scaled image justification, such as ; Centre, Top Left, Top Right etc.

**Comment by josephdadams** [comment]
I've added this in v2.2.0 of the module. Cheers!
