### ISSUE TITLE
Module Request: Blackmagic Design Teranex AV

### ISSUE THREAD

**Issue by rcharters** [bitfocus/companion-module-bmd-teranex#4]
**Describe the feature**
Module to control Blackmagic Design Teranex Products, specifically the Teranex AV.
Teranex AV is a video format converter with many other functions, such as color control, audio embedding, timecode control, closed captioning etc.

Initially commands to control Preset Groups in the Teranex AV would be most useful.

**Is this platform dependent (windows, mac, ..)?**
Not Platform Dependent

**If documentation is required to implement, do you know where to find it?**
Protocol to control the Teranex AV is TCP based, and is similar to other Blackmagic Design products such as the Videohub and ATEM products. There is a protocol in the Blackmagic Design Manual for the Teranex Products: https://documents.blackmagicdesign.com/UserManuals/TeranexManual.pdf

**Usecases**
When using multiple Teranex AVs in a production environment, the ability to remotely control the units is desired. Blackmagic Design has a software environment for this purpose, but it is very limited.

Teranex AVs can be used in many instances, such as an interface from a computer to a projector. Converting 4K to HD or HD to 4K. Embedding audio to an HDI SDI Stream. Plus many many more.

**Comment by gabonacorp** [comment]
Hi folks,

I just want to bump this issue. Teranex AV needs two options for SDI input selection. Could check this again please?

Thanks and best,

Andras

**Comment by gabonacorp** [comment]
One quick update:

If I use Teranex instance and setup the IP properly at the List of Dynamic Variables panel the current value of the video_input variable is correct. It's changes between SDI1 and SDI2. The only problem is that if I use this video input action at the Options dropdown there is only SDI, no SDI1 and SDI2. This is the only thing what suppose to be change.

Thanks for all your effort helping me solve this.

Best,

Andras

**Comment by gabonacorp** [comment]
One quick update:

If I use Teranex instance and setup the IP properly at the List of Dynamic Variables panel the current value of the video_input variable is correct. It's changes between SDI1 and SDI2. The only problem is that if I use this video input action there is no SDI1 and SDI2 in the dropdown list but only SDI.

Could you help me to solve this please?

Thanks and best,

Andras
