### ISSUE TITLE
Duplicate Entry - No 1080p60

### ISSUE THREAD

**Issue by ColinMulcahy** [bitfocus/companion-module-bmd-teranex#9]
Hi,

Using a Teranex AV.

When selecting Output Format on an action, the dropdown list seems to have a duplicate entry for 1080p 59.94hz and does not have 1080p 60hz.

{ id: '1080p59.94', label: '1080p 59.94hz' },
{ id: '1080i60', label: '1080i 50hz' },
{ id: '1080p60', label: '1080p 50hz' },
{ id: '1080p59.94', label: '1080p 59.94hz' },

**Comment by josephdadams** [comment]
I have this fixed in the latest.
